/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

export const TUI_COPY_RESOURCES = {
  'mcp-status': {
    en: {
      title: 'MCP SERVERS',
      footer: {
        back: 'Esc back',
        readOnly: '↑/↓ scroll · q/Esc close',
        manage:
          'a Add · Enter Edit · Space Enable/disable · t Test · r Reconnect · d Remove · Esc Close',
      },
      unavailableTitle: 'This TUI is not connected to a local MCP control plane.',
      unavailableDetail:
        'Client MCP tool association for remote Runtime Hosts is planned for a later release.',
      loading: 'Loading mcp.json and discovering tools…',
      loadError:
        'MCP configuration could not be loaded; no tools were published to the Runtime Host.',
      noServers: 'No MCP servers are configured. Press a to add one.',
      publication: {
        waiting: 'waiting to publish',
        host_unavailable: 'Runtime Host reconnecting',
        publishing: 'publishing',
        published: 'published',
        not_published: 'not published',
        error: 'publication failed',
      },
      serverState: {
        disabled: 'disabled',
        disconnected: 'disconnected',
        connecting: 'connecting',
        connected: 'connected',
        'needs-auth': 'needs-auth',
        error: 'error',
      },
      configuredOnly: 'configured only',
      configPending: 'config pending',
      toolCount: '{count, plural, one {# tool} other {# tools}}',
    },
    zh: {
      title: 'MCP 服务器',
      footer: {
        back: 'Esc 返回',
        readOnly: '↑/↓ 滚动 · q/Esc 关闭',
        manage: 'a 添加 · Enter 编辑 · Space 启用/停用 · t 测试 · r 重连 · d 删除 · Esc 关闭',
      },
      unavailableTitle: '当前 TUI 未连接本地 MCP 控制面。',
      unavailableDetail: '远程 Runtime Host 的客户端 MCP 工具关联将在后续版本提供。',
      loading: '正在读取 mcp.json 并发现工具…',
      loadError: '无法读取或应用 MCP 配置；没有向 Runtime Host 发布工具。',
      noServers: '尚未配置 MCP 服务器。按 a 添加。',
      publication: {
        waiting: '等待发布',
        host_unavailable: 'Runtime Host 重连中',
        publishing: '正在发布',
        published: '已发布',
        not_published: '未发布',
        error: '发布失败',
      },
      serverState: {
        disabled: '已停用',
        disconnected: '未连接',
        connecting: '连接中',
        connected: '已连接',
        'needs-auth': '需要登录',
        error: '错误',
      },
      configuredOnly: '仅已配置',
      configPending: '配置待同步',
      toolCount: '{count} 个工具',
    },
  },
  pickers: {
    en: {
      modelPickerTitle: 'Select Model',
      modelSwitchCacheWarning:
        '⚠ Switching models may rebuild the prompt cache; the next request may be slower or cost more.',
      modelSearchHint:
        'Search models / providers / connections · ↑↓ select · Enter confirm · Esc cancel',
      searchLabel: 'Search',
      noMatchingModels: 'No matching models',
      selectPickerHint: '↑↓ select · Enter confirm · Esc close',
      providerConfigured: 'configured',
      addAccount: 'add account',
      thinkingLevels: {
        off: 'Off',
        minimal: 'Minimal',
        low: 'Low',
        medium: 'Medium',
        high: 'High',
        xhigh: 'Extra high',
        max: 'Maximum',
      },
      defaultThinkingLevel: 'Default',
      thinkingPickerTitle: 'Select Thinking Level',
      currentMarker: 'current',
      defaultMarker: 'default',
      setupTitle: 'Set Up Provider',
      baseUrlLabel: 'Base URL',
      apiKeyLabel: 'API key',
      onboardingUnavailable:
        'Onboarding is unavailable: this environment does not provide a setup surface.',
      onboardingRequestFailed: 'Could not reach the Runtime Host. Try again.',
      onboardingRejections: {
        provider_unsupported: 'This provider does not support API-key onboarding.',
        connection_not_found: 'This connection no longer exists. Reopen /setup and try again.',
        credential_not_configured: 'An API key is required.',
        base_url_not_configured: 'A Base URL is required for this provider.',
        catalog_full: 'The connection catalog is full.',
        model_unavailable: 'A selected model is no longer available. Verify and select again.',
        superseded: 'This connection changed. Reopen /setup and try again.',
      },
      onboardingFailures: {
        auth: 'Provider authentication failed. Check the API key and try again.',
        timeout: 'Provider verification timed out. Try again.',
        provider_unavailable: 'The provider is unavailable. Try again later.',
        network: 'A network error interrupted provider verification. Try again.',
        invalid_response: 'The provider returned an invalid response. Try again.',
        unknown: 'Provider verification failed. Try again.',
      },
      accountSavedRefreshFailed:
        'Account saved, but the model list has not refreshed. Restart Sharker to reload it.',
      listProvidersFailed: 'Could not read configured connections.',
      noConfigurableProviders: 'No configurable API key providers are available.',
      baseUrlRequired: 'Enter a Base URL',
      baseUrlInvalid: 'Base URL is not a valid URL',
      baseUrlProtocol: 'Base URL must use http or https',
      baseUrlCredentials: 'Base URL cannot include credentials',
      baseUrlQuery: 'Base URL cannot include a query or fragment',
      baseUrlTooLong: 'Base URL cannot exceed 2048 bytes',
      selectModelBeforeSaving: 'Select at least one model before saving',
      reuseBaseUrlHint:
        'Leave blank to reuse the saved Base URL, or enter a replacement · Esc returns to provider selection',
      enterBaseUrlHint: 'Enter the relay Base URL (http/https) · Esc returns to provider selection',
      continueAction: 'Enter to continue',
      providerSearchHint: 'Search providers · ↑↓ select · Enter confirm · Esc cancel',
      noMatchingProviders: 'No matching providers',
      keyHints: {
        reuse: {
          baseUrl:
            'Leave blank to reuse the saved key, or enter a new key to rotate it · Esc returns to Base URL',
          provider:
            'Leave blank to reuse the saved key, or enter a new key to rotate it · Esc returns to provider selection',
        },
        enter: {
          baseUrl: 'Enter an API key · stored only on this machine · Esc returns to Base URL',
          provider:
            'Enter an API key · stored only on this machine · Esc returns to provider selection',
        },
      },
      submitAction: 'Enter to submit',
      verifyingKey: 'Verifying key…',
      modelSelectionHint: 'Search models · ↑↓ select · Space toggle · Enter save · Esc back',
      selectedModels: '{count} selected',
      selectedModelsAndSave: '{count} selected · Enter to save',
      saving: 'Saving…',
      complete: 'Complete',
      enabledModels: 'Models enabled: {count}',
      closeAction: 'Enter to close',
      thinkingUnsupported: 'This model does not support changing the thinking level.',
    },
    zh: {
      modelPickerTitle: '选择模型',
      modelSwitchCacheWarning: '⚠ 切换模型可能需要重建提示缓存；下一次请求可能更慢或成本更高。',
      modelSearchHint: '搜索模型 / 服务商 / 连接 · ↑↓ 选择 · Enter 确认 · Esc 取消',
      searchLabel: '搜索',
      noMatchingModels: '没有匹配的模型',
      selectPickerHint: '↑↓ 选择 · Enter 确认 · Esc 关闭',
      providerConfigured: '已设置',
      addAccount: '添加账号',
      thinkingLevels: {
        off: '关',
        minimal: '最小',
        low: '低',
        medium: '中',
        high: '高',
        xhigh: '超高',
        max: '最高',
      },
      defaultThinkingLevel: '默认',
      thinkingPickerTitle: '选择思考级别',
      currentMarker: '当前',
      defaultMarker: '默认',
      setupTitle: '配置模型提供商',
      baseUrlLabel: 'Base URL',
      apiKeyLabel: 'API key',
      onboardingUnavailable: 'Onboarding 不可用：当前运行环境未提供配置入口。',
      onboardingRequestFailed: '无法连接 Runtime Host，请重试。',
      onboardingRejections: {
        provider_unsupported: '该服务商不支持 API key 配置。',
        connection_not_found: '该连接已不存在，请重新打开 /setup 后重试。',
        credential_not_configured: '需要填写 API key。',
        base_url_not_configured: '该服务商需要填写 Base URL。',
        catalog_full: '连接目录已满。',
        model_unavailable: '所选模型已不可用，请重新验证并选择。',
        superseded: '该连接已发生变化，请重新打开 /setup 后重试。',
      },
      onboardingFailures: {
        auth: '服务商身份验证失败，请检查 API key 后重试。',
        timeout: '服务商验证超时，请重试。',
        provider_unavailable: '服务商当前不可用，请稍后重试。',
        network: '网络错误中断了服务商验证，请重试。',
        invalid_response: '服务商返回了无效响应，请重试。',
        unknown: '服务商验证失败，请重试。',
      },
      accountSavedRefreshFailed: '账号已保存，但模型列表暂未刷新。重启 Sharker 后会重新载入。',
      listProvidersFailed: '无法读取已配置的连接。',
      noConfigurableProviders: '没有可配置的 API key 类供应商。',
      baseUrlRequired: '需要填写 Base URL',
      baseUrlInvalid: 'Base URL 不是有效的 URL',
      baseUrlProtocol: 'Base URL 必须使用 http 或 https',
      baseUrlCredentials: 'Base URL 不能包含账号密码',
      baseUrlQuery: 'Base URL 不能包含查询串或片段',
      baseUrlTooLong: 'Base URL 不能超过 2048 字节',
      selectModelBeforeSaving: '至少选择一个模型再保存',
      reuseBaseUrlHint: '留空复用已保存的 Base URL，或输入新地址替换 · Esc 返回选择服务商',
      enterBaseUrlHint: '输入中转站的 Base URL（http/https）· Esc 返回选择服务商',
      continueAction: 'Enter 继续',
      providerSearchHint: '搜索服务商，↑↓ 选择 · Enter 确认 · Esc 取消',
      noMatchingProviders: '没有匹配的服务商',
      keyHints: {
        reuse: {
          baseUrl: '留空复用已保存的 key，或输入新 key 轮换 · Esc 返回 Base URL',
          provider: '留空复用已保存的 key，或输入新 key 轮换 · Esc 返回选择服务商',
        },
        enter: {
          baseUrl: '输入 API key · 仅本机存储 · Esc 返回 Base URL',
          provider: '输入 API key · 仅本机存储 · Esc 返回选择服务商',
        },
      },
      submitAction: 'Enter 提交',
      verifyingKey: '正在验证 key…',
      modelSelectionHint: '搜索模型，↑↓ 选择 · Space 切换 · Enter 保存 · Esc 返回',
      selectedModels: '已选 {count}',
      selectedModelsAndSave: '已选 {count} · Enter 保存',
      saving: '正在保存…',
      complete: '完成',
      enabledModels: '已启用模型：{count}',
      closeAction: 'Enter 关闭',
      thinkingUnsupported: '当前模型不支持思考级别切换。',
    },
  },
  'primary-guidance': {
    en: {
      welcome: {
        tagline: 'Get things done together',
        start: 'Type a message to start',
        session: 'Switch or resume a session',
        model: 'Switch models',
        setup: 'Set up a model provider',
      },
      commands: {
        compact: 'Compact session context',
        context: 'Show latest request context usage',
        exit: 'Exit Sharker',
        goal: 'Show autonomous goal status',
        graph: 'Show, enable, disable, or run one Graph turn',
        help: 'Show commands and keybindings',
        mcp: 'Manage client-owned MCP servers and tool publication status',
        model: 'Select model',
        move: 'Move current session to another directory',
        new: 'Start a new session',
        permissions: 'Set session permissions',
        recap: 'One-sentence recap of the session so far',
        rename: 'Rename current session',
        resume: 'Resume latest interrupted run at a safe boundary',
        rewind: 'Rewind to an earlier turn',
        session: 'Resume session',
        setup: 'Set up a model provider (API key)',
        side: 'Open a temporary side conversation',
        skill: 'Invoke a skill (or type /skill:<name> inline)',
        swarm: 'Show, enable, disable, or run one Swarm turn',
        thinking: 'Set thinking level',
        transcript: 'Browse the full transcript inside Sharker',
      },
      help: {
        commandsHeading: 'Commands',
        userCommand: '  !<command> — run one shell command visible only to you',
        keybindingsHeading: 'Keybindings',
        keybindings: [
          '  Ctrl+O — expand or collapse all tool output',
          '  Ctrl+T — expand or collapse all thinking in view',
          '  Scroll the transcript with your terminal or trackpad',
          '  Enter (during a turn) — steer: inject a message into the running turn',
          '  Alt+Enter (during a turn) — queue a message for the next turn',
          '  Alt+↑ — take queued messages back into the editor to re-edit',
          '  Esc Esc (during a turn) — interrupt the turn',
          '  Esc Esc (when idle) — rewind to an earlier turn',
          '  Ctrl+C — stop the turn, clear input, or press twice to exit',
          '  Ctrl+D — exit when input is empty',
        ],
      },
    },
    zh: {
      welcome: {
        tagline: '陪你把事做完',
        start: '输入消息开始对话',
        session: '切换或恢复会话',
        model: '切换模型',
        setup: '配置模型提供商',
      },
      commands: {
        compact: '压缩会话上下文',
        context: '查看最近一次请求的上下文用量',
        exit: '退出 Sharker',
        goal: '查看自主目标状态',
        graph: '查看、启用、停用 Graph 模式，或执行一次 Graph 任务',
        help: '查看命令和快捷键',
        mcp: '管理客户端 MCP 服务器和工具发布状态',
        model: '选择模型',
        move: '将当前会话移到其他目录',
        new: '新建会话',
        permissions: '设置会话权限',
        recap: '用一句话总结当前会话',
        rename: '重命名当前会话',
        resume: '从安全边界恢复最近一次中断的执行',
        rewind: '回退到较早的对话轮次',
        session: '切换或恢复会话',
        setup: '配置模型提供商（API Key）',
        side: '打开临时 Side Conversation',
        skill: '调用 Skill（也可直接输入 /skill:<name>）',
        swarm: '查看、启用、停用 Swarm 模式，或执行一次 Swarm 任务',
        thinking: '设置思考级别',
        transcript: '在 Sharker 内浏览完整对话记录',
      },
      help: {
        commandsHeading: '命令',
        userCommand: '  !<command> — 执行一次仅用户可见的 shell 命令',
        keybindingsHeading: '快捷键',
        keybindings: [
          '  Ctrl+O — 展开或折叠所有工具输出',
          '  Ctrl+T — 展开或折叠视图中的所有思考块',
          '  使用终端或触控板滚动对话记录',
          '  Enter（任务运行中）— 将消息注入当前任务',
          '  Alt+Enter（任务运行中）— 将消息排入下一轮',
          '  Alt+↑ — 将已排队消息取回编辑器重新编辑',
          '  Esc Esc（任务运行中）— 中断当前任务',
          '  Esc Esc（空闲时）— 回退到较早的轮次',
          '  Ctrl+C — 停止任务、清空输入，或连续按两次退出',
          '  Ctrl+D — 输入为空时退出',
        ],
      },
    },
  },
  'session-status': {
    en: {
      running: 'running',
      waitingForUser: 'waiting for you',
      permissionRequired: 'needs permission',
      connectionRequired: 'needs connection',
      signInRequired: 'needs sign-in',
      stopped: 'stopped',
    },
    zh: {
      running: '进行中',
      waitingForUser: '等你确认',
      permissionRequired: '需要权限',
      connectionRequired: '需要连接',
      signInRequired: '需要重新登录',
      stopped: '已中止',
    },
  },
} as const;
