/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/renderer/astryx-theme/sharkerTheme.ts
 * Command: astryx theme build src/renderer/astryx-theme/sharkerTheme.ts --out src/renderer/astryx-theme/sharker.css
 * CLI: @astryxdesign/cli@0.4.5
 * Core: @astryxdesign/core@0.1.0
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const neutralIconRegistry: IconRegistry;
export declare const sharkerTheme: DefinedTheme;
