/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { CallToolRequestSchema, ListToolsRequestSchema } from '@modelcontextprotocol/sdk/types.js';
import { installStdioFixtureEvents } from './stdio-fixture-events.js';

installStdioFixtureEvents('legacy');

if (process.argv.includes('--crash')) {
  process.stderr.write('fixture startup failed: deliberate diagnostic\n');
  process.exit(23);
}
if (process.argv.includes('--crash-secret-tail')) {
  process.stderr.write('token=sk-live-secret-token-value');
  process.exit(24);
}
if (process.argv.includes('--crash-hostile-stderr')) {
  process.stderr.write(`${'x'.repeat(1_998)}sk`);
  await new Promise((resolve) => setTimeout(resolve, 25));
  process.stderr.write('-live-secret-token-value\r\u2028\u206a\n');
  process.stderr.write(`${'z'.repeat(10_000)}\n`);
  process.stderr.write('after\u2029line\n');
  process.stderr.write('sk-live-\u001b12345678\n');
  process.stderr.write('AWS_SECRET_ACCESS_KEY\\\n=environment-secret\n');
  process.stderr.write('aws configure set aws_secret_access_key \\\ncontinued-secret\n');
  process.exit(25);
}
if (process.argv.includes('--crash-many-stderr-lines')) {
  process.stderr.write('x\n'.repeat(1_000));
  process.exit(26);
}
if (process.argv.includes('--slow-start')) {
  await new Promise((resolve) => setTimeout(resolve, 30_000));
}

const server = new Server(
  { name: 'maka-mcp-fixture', version: '1.0.0' },
  { capabilities: { tools: { listChanged: true } } },
);

server.setRequestHandler(ListToolsRequestSchema, async ({ params }) => {
  if (process.argv.includes('--schema-annotations')) {
    return {
      tools: [
        {
          name: 'annotated',
          inputSchema: {
            $schema: 'http://json-schema.org/draft-07/schema#',
            $comment: 'Generated by the TypeScript SDK schema converter.',
            $id: 'https://example.com/annotated.schema.json',
            type: 'object' as const,
            properties: {
              value: {
                $schema: 'http://json-schema.org/draft-07/schema#',
                type: 'string' as const,
              },
            },
            patternProperties: {
              '^tag:': {
                $comment: 'Matches tagged string properties.',
                type: 'string' as const,
              },
            },
            dependentSchemas: {
              value: {
                $schema: 'https://json-schema.org/draft/2020-12/schema',
                required: ['dependent'],
              },
            },
            dependencies: {
              value: {
                $schema: 'http://json-schema.org/draft-07/schema#',
                required: ['detail'],
              },
              detail: ['value'],
            },
            prefixItems: [
              {
                $comment: 'The first tuple item.',
                type: 'string' as const,
              },
            ],
            additionalItems: {
              $comment: 'Constrain additional tuple items.',
              type: 'integer' as const,
            },
            unevaluatedItems: {
              $schema: 'https://json-schema.org/draft/2020-12/schema',
              type: 'boolean' as const,
            },
            contains: {
              $schema: 'https://json-schema.org/draft/2020-12/schema',
              type: 'number' as const,
            },
            not: {
              $comment: 'Disallow the forbidden property.',
              required: ['forbidden'],
            },
            if: {
              $schema: 'https://json-schema.org/draft/2020-12/schema',
              required: ['value'],
            },
            then: {
              $comment: 'Require detail when value is present.',
              required: ['detail'],
            },
            else: {
              $schema: 'https://json-schema.org/draft/2020-12/schema',
              required: ['fallback'],
            },
            unevaluatedProperties: {
              $comment: 'Constrain unevaluated properties.',
              type: 'boolean' as const,
            },
          },
        },
      ],
    };
  }
  if (!params?.cursor) {
    return {
      tools: [
        tool('echo', 'Echo text', true),
        tool('rich', 'Return rich content', true),
        ...(process.argv.includes('--environment')
          ? [tool('environment', 'Read selected environment variables', true)]
          : []),
      ],
      nextCursor: 'page-2',
    };
  }
  if (params.cursor === 'page-2') {
    return {
      tools: [tool('fail', 'Return MCP isError', false), tool('slow', 'Wait until aborted', false)],
    };
  }
  throw new Error('unexpected cursor');
});

server.setRequestHandler(CallToolRequestSchema, async ({ params }) => {
  if (params.name === 'echo') {
    return {
      content: [{ type: 'text', text: String(params.arguments?.value ?? '') }],
      structuredContent: { echoed: params.arguments?.value },
    };
  }
  if (params.name === 'rich') {
    return {
      content: [
        { type: 'text', text: 'hello' },
        { type: 'image', data: 'aW1hZ2U=', mimeType: 'image/png' },
        { type: 'audio', data: 'YXVkaW8=', mimeType: 'audio/wav' },
        {
          type: 'resource',
          resource: { uri: 'file:///fixture.txt', text: 'resource text', mimeType: 'text/plain' },
        },
        {
          type: 'resource_link',
          uri: 'https://example.com/item',
          name: 'item',
          mimeType: 'text/html',
        },
      ],
    };
  }
  if (params.name === 'fail') {
    // With FIXTURE_LEAK_TOKEN set, behaves like a server echoing a secret
    // it was handed — the manager must scrub it out of the tool error.
    const leak = process.env.FIXTURE_LEAK_TOKEN ? ` ${process.env.FIXTURE_LEAK_TOKEN}` : '';
    return { isError: true, content: [{ type: 'text', text: `deliberate failure${leak}` }] };
  }
  if (params.name === 'slow') {
    await new Promise((resolve) => setTimeout(resolve, 30_000));
    return { content: [{ type: 'text', text: 'too late' }] };
  }
  if (params.name === 'environment') {
    const names = Array.isArray(params.arguments?.names) ? params.arguments.names : [];
    return {
      content: [
        {
          type: 'text',
          text: JSON.stringify(
            Object.fromEntries(
              names
                .filter((name): name is string => typeof name === 'string')
                .map((name) => [name, process.env[name] ?? null]),
            ),
          ),
        },
      ],
    };
  }
  return { isError: true, content: [{ type: 'text', text: 'unknown tool' }] };
});

function tool(name: string, description: string, readOnlyHint: boolean) {
  return {
    name,
    description,
    inputSchema: { type: 'object' as const, properties: { value: { type: 'string' } } },
    annotations: { readOnlyHint },
  };
}

await server.connect(new StdioServerTransport());

if (process.argv.includes('--runtime-stderr')) {
  setTimeout(() => process.stderr.write('runtime diagnostic\n'), 500);
}
