// @generated by scripts/gen-bundled-skill-catalog.mjs — do not edit by hand.
// Source of truth: packages/runtime/resources/bundled-skills/<id>/SKILL.md
// Regenerate: npm run generate:bundled-skills

export interface BundledSkillSource {
  id: string;
  body: string;
  sourceName: string;
  sourceVersion: string;
  contentSha256: string;
  legacyContentSha256: readonly string[];
}

// biome-ignore format: generated catalog keeps one reviewable source per line.
export const BUNDLED_SKILL_CATALOG: ReadonlyArray<BundledSkillSource> = [

];
