import { describe, expect, it } from 'vitest'
import { filterPaletteCommands, PALETTE_COMMANDS } from './command-palette'

describe('command palette', () => {
  it('lists review, mention and settings', () => {
    const ids = PALETTE_COMMANDS.map((c) => c.id)
    expect(ids).toContain('review')
    expect(ids).toContain('mention')
    expect(ids).toContain('skill')
    expect(ids).toContain('settings')
    expect(ids).toContain('find')
    expect(ids).toContain('search-chats')
    expect(ids).toContain('dictate')
    expect(ids).toContain('voice-chat')
    expect(ids).toContain('popout')
    expect(ids).toContain('agents')
    expect(ids).toContain('personality')
    expect(ids).toContain('shortcuts')
    expect(ids).toContain('fork')
    expect(ids).toContain('status')
    expect(ids).toContain('goal')
    expect(ids).toContain('diff')
    expect(ids).toContain('open-worktree')
    expect(ids).toContain('create-branch')
    expect(ids).toContain('mcp')
    expect(ids).toContain('feedback')
    expect(ids).toContain('local')
    expect(ids).toContain('worktree')
    expect(ids).toContain('side')
    expect(ids).toContain('archive')
    expect(ids).toContain('init')
    expect(ids).toContain('permissions')
    expect(ids).toContain('memories')
    expect(ids).toContain('copy')
    expect(ids).toContain('resume')
    expect(ids).toContain('compact')
    expect(ids).toContain('delete')
    expect(ids).toContain('theme')
    expect(ids).toContain('debug-config')
    expect(ids).toContain('fast')
    expect(ids).toContain('skills')
    expect(ids).toContain('stop')
    expect(ids).toContain('nav-back')
    expect(ids).toContain('nav-forward')
    expect(ids).toContain('font-larger')
    expect(ids).toContain('clear-terminal')
    expect(ids).toContain('clear-unread')
    expect(ids).toContain('search-files')
    expect(ids).toContain('next-attention')
    expect(ids).toContain('approve')
    expect(ids).toContain('rename')
    expect(ids).toContain('pin')
    expect(ids).toContain('unread')
    expect(ids).toContain('standalone')
    expect(ids).toContain('usage')
    expect(ids).toContain('copy-cwd')
    expect(ids).toContain('copy-session')
    expect(ids).toContain('copy-deeplink')
  })

  it('filters by title and keywords', () => {
    expect(filterPaletteCommands('审查').some((c) => c.id === 'review')).toBe(true)
    expect(filterPaletteCommands('terminal').some((c) => c.action === 'toggle_terminal')).toBe(true)
    expect(filterPaletteCommands('zzz-none')).toEqual([])
  })
})
