/**
 * 主进程与渲染进程 IPC channel 名称常量。
 * 详见 shared/README.md
 */
/** 主进程与渲染进程 IPC channel 名称 */
export const IPC = {
  GET_SETTINGS: 'settings:get',
  SAVE_SETTINGS: 'settings:save',
  TEST_PROVIDER: 'provider:test',
  SEND_MESSAGE: 'chat:send',
  ABORT_CHAT: 'chat:abort',
  APPROVAL_RESPONSE: 'approval:response',
  SELECT_WORKSPACE: 'workspace:select',
  PICK_WORKSPACE_FOLDER: 'workspace:pick',
  LIST_CONVERSATIONS: 'conversations:list',
  LOAD_CONVERSATION: 'conversations:load',
  SAVE_CONVERSATION: 'conversations:save',
  DELETE_CONVERSATION: 'conversations:delete',
  SET_ACTIVE_CONVERSATION: 'conversations:set-active',
  CREATE_CONVERSATION: 'conversations:create',
  GENERATE_TITLE: 'conversations:generate-title',
  IMPORT_SKILL_REPO: 'skills:import',
  RELOAD_SKILLS: 'skills:reload',
  WINDOW_MINIMIZE: 'window:minimize',
  WINDOW_MAXIMIZE: 'window:maximize',
  WINDOW_CLOSE: 'window:close',
  OPEN_EXTERNAL: 'shell:open-external',
  GET_MCP_CONFIG: 'mcp:get-config',
  SAVE_MCP_CONFIG: 'mcp:save-config',
  TEST_MCP_CONFIG: 'mcp:test-config',
  GET_COMPUTER_USE_STATUS: 'computer-use:status',
  GET_BROWSER_USE_STATUS: 'browser-use:status',
  INSTALL_BROWSER_USE_MANIFEST: 'browser-use:install-manifest',
  LIST_MCP_PLUGINS: 'mcp:list-plugins',
  TOGGLE_MCP_PLUGIN: 'mcp:toggle-plugin',
  COMPRESS_CONTEXT: 'chat:compress-context',
  GET_TOKEN_USAGE: 'usage:token-history',
  WORKSPACE_TREE: 'workspace:tree',
  READ_TEXT_FILE: 'workspace:read-text-file',
  GIT_BRANCH_INFO: 'git:branch-info',
  GIT_LIST_BRANCHES: 'git:list-branches',
  GIT_CHECKOUT: 'git:checkout',
  TERMINAL_CREATE: 'terminal:create',
  TERMINAL_WRITE: 'terminal:write',
  TERMINAL_RESIZE: 'terminal:resize',
  TERMINAL_KILL: 'terminal:kill',
  LIST_AUTOMATIONS: 'automations:list',
  SAVE_AUTOMATIONS: 'automations:save',
  LIST_HOOKS: 'hooks:list',
  SAVE_HOOKS: 'hooks:save',
  OAUTH_GPT_META: 'oauth-gpt:meta',
  OAUTH_GPT_START: 'oauth-gpt:start',
  REMOTE_COLLAB_GET: 'remote-collab:get',
  REMOTE_COLLAB_CREATE: 'remote-collab:create',
  LSP_START: 'lsp:start',
  LSP_STATUS: 'lsp:status',
  LSP_STOP: 'lsp:stop'
} as const
