import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import {
  LOCAL_ENVIRONMENT_REL,
  localEnvironmentTomlPath,
  parseLocalEnvironmentCleanupScript,
  parseLocalEnvironmentSetupScript
} from './local-environment'

describe('local environment setup script', () => {
  it('reads [setup] script and ignores empty or missing tables', () => {
    expect(parseLocalEnvironmentSetupScript('')).toBe('')
    expect(
      parseLocalEnvironmentSetupScript(
        '# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY\nversion = 1\nname = "codex"\n\n[setup]\nscript = ""\n\n[[actions]]\nname = "Run"\n'
      )
    ).toBe('')
    expect(
      parseLocalEnvironmentSetupScript('[setup]\nscript = "npm install\\nnpm run build"\n')
    ).toBe('npm install\nnpm run build')
    expect(
      parseLocalEnvironmentSetupScript('[setup]\nscript = """\nnpm install\nnpm run build\n"""\n')
    ).toBe('npm install\nnpm run build')
    expect(parseLocalEnvironmentSetupScript('[cleanup]\nscript = "echo no"\n')).toBe('')
    expect(parseLocalEnvironmentCleanupScript('[cleanup]\nscript = "scripts/worktree-down.sh"\n')).toBe(
      'scripts/worktree-down.sh'
    )
    expect(
      parseLocalEnvironmentCleanupScript('[setup]\nscript = "up"\n[cleanup]\nscript = "down"\n')
    ).toBe('down')
    expect(parseLocalEnvironmentCleanupScript('[setup]\nscript = "up"\n')).toBe('')
    expect(localEnvironmentTomlPath('/repo')).toBe(join('/repo', LOCAL_ENVIRONMENT_REL))
    const wtSrc = readFileSync(
      join(dirname(fileURLToPath(import.meta.url)), '../tools/thread-worktree.ts'),
      'utf8'
    )
    expect(wtSrc).toContain('parseLocalEnvironmentScript')
    expect(wtSrc).toContain("runLocalEnvironmentScript(cwd, dest, 'cleanup')")
    expect(wtSrc).toContain('localEnvironmentTomlPath')
    expect(wtSrc.includes('[[actions]]')).toBe(false)
  })
})
